### ISSUE TITLE
Identities yaml should not be cached in memory

### ISSUE THREAD

**Issue by clintecker** [sstephenson/hector#12]
The current behavior loads the username and passwords into memory the first time Identity::find is called which is when the first user connects.

If you want to add a new user after the point, you must restart the server to pick up the changes.

**Comment by leedo** [comment]
Keeping them in memory seems like a good idea to me. Maybe we could just check the mtime on the yaml file each time and reload if it has changed?

**Comment by leedo** [comment]
https://github.com/leedo/hector/commit/e28843347156789a8ef211cec864827e816488d9 implements mtime tracking
