### ISSUE TITLE
Add support for unicode channels and unicode usernames

### ISSUE THREAD

**Issue by clintecker** [sstephenson/hector#13]
Small change in Channel to support channels, unknown for usernames.

**Comment by clintecker** [comment]
I'll be starting work on this in a unicode branch in my repo

**Comment by clintecker** [comment]
Done here with tests: https://github.com/clintecker/hector/commits/unicode

**Comment by raws** [comment]
This issue is so old that it's even got Ruby 1.9 support

edit: ya dingus

**Comment by clintecker** [comment]
you are
