### ISSUE TITLE
Hector hecting hected hector hectest

### ISSUE THREAD

**Issue by wsc** [sstephenson/hector#15]
seriously weird dude.

http://willstclair.com/img/hectoke1.png
http://willstclair.com/img/hectoke2.png

i did make an (unrelated i think?) change to etoke in sam's membershiphandler because @prefixes was nil and it was unhappy fuck if i know what that is

```
    def on_353 # RPL_NAMREPLY
      response.text.split.each do |nick|
        nick = nick.sub(/^[#{Regexp.escape(@prefixes)}]+/, "") unless !@prefixes
        add_membership(response.args[2], nick)
      end
    end
```

also i added PASS before USER because hector.

**Comment by clintecker** [comment]
So is the issue that Hector is stripping out IRC color codes or something? Also I'm pretty sure you can issue PASS/USER/NICK in any order.

**Comment by clintecker** [comment]
Can you paste in the output of Hector?

**Comment by clintecker** [comment]
I tried this out and it seemed to work fine.  I send the codes from Colloquy and then read them back out in Alice: http://clintecker.com/hector-colors-20100224-152517.png

**Comment by wsc** [comment]
Hector:

<pre>
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [127.0.0.1:59880] (wsc) received "PRIVMSG #hector etoke"
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [10.23.8.1:32935] (etoke) sent ":wsc!wsc@hector PRIVMSG #hector :etoke\r\n"
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [10.23.8.1:32935] (etoke) received "PRIVMSG #hector \0030,3 \002 _\\|/_ : wsc wants to etoke!!!!!!"
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [127.0.0.1:59880] (wsc) sent ":etoke!etoke@hector PRIVMSG #hector : wsc wants to etoke!!!!!!\r\n"
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [10.23.8.1:32935] (etoke) received "PRIVMSG #hector if you want to smoek, say `etoke'; `etoke warning' to continue"
  D, [2010-02-24 16:30:28#11801] DEBUG -- : [127.0.0.1:59880] (wsc) sent ":etoke!etoke@hector PRIVMSG #hector :continue\r\n"

</pre>

**Comment by wsc** [comment]
It's not just the color codes: http://willstclair.com/img/tok3.png

the line <pre>if you want to smoek, say `etoke';`etoke warning' to continue</pre> doesn't have any color codes, but still only shows up as "continue" in Alice.

**Comment by clintecker** [comment]
It looks like the problem is probably that the irc lib wsc is using isn't prepending the text of the response with a colon

**Comment by wsc** [comment]
dang. http://github.com/wsc/etoke/commit/3a25e40637d6488a403afbb3e40ae2dfa8edb893
