### ISSUE TITLE
plugin support

### ISSUE THREAD

**Issue by trvsdnn** [sstephenson/hector#29]
Any plans/thoughts on adding general plugin support?

Looking to extend in a few different ways, but some of the things I want to add shouldn't be part of hector "core", they feel more like plugins.

**Comment by trvsdnn** [comment]
Or, I could just manually extend it, like so: https://github.com/raws/hector-statsd

Just seems like a more official plugin structure would save trouble when a new version is released.

**Comment by raws** [comment]
If that's something you're interested in tackling, go for it! Hector is currently a comfortably stable project which fulfills its maintainers' stated goal, which is to be a simple private chat server for friends. But if you come up with a well-tested, unobtrusive method of extending Hector which respects its spirit, I'll certainly want to take a look at it.

If it feels like Hector, maybe it should be a part of Hector. If not, well, fork away and enjoy the fruits of your labor!
