### ISSUE TITLE
Split up 353 responses for NAMES

### ISSUE THREAD

**Issue by sstephenson** [sstephenson/hector#3]
Split up 353 responses so that each response fits into a 512-char line.

**Comment by raws** [comment]
512 _characters_ is actually 512 _bytes_ according to RFC 1459. Is Hector taking a different approach?

Also, is there a need for a global mechanism to split responses into appropriately-sized chunks?

**Comment by ryanfb** [comment]
In 1.8 Strings are just byte sequences and I believe 1.8 String#split/length will do exactly what is expected (in the sense of bytes v. characters) as far as the RFC goes.

**Comment by raws** [comment]
Correct. 1.8's String behavior has worked without a hitch in other IRC projects. I was clarifying what the RFC requires, just in case.
