### ISSUE TITLE
How do get ride of "File is missing" message

### ISSUE THREAD

**Issue by postmodern** [sstephenson/hector#36]
I notice that the default MOTD is "File is missing".

https://github.com/sstephenson/hector/blob/master/lib/hector/concerns/presence.rb#L40

**Comment by leedo** [comment]
Hector does not support a MOTD, but some clients require either a MOTD or "File is missing" message.

**Comment by postmodern** [comment]
how could I go about adding one? I suppose I would need a `Hector.motd` variable and read from that?

**Comment by djanowski** [comment]
Would you take a patch for including a MOTD? It's a nice feature for hackers :)

**Comment by raws** [comment]
@djanowski If the patch is not too intrusive and includes thorough test coverage, sure!

**Comment by raws** [comment]
I'm closing this issue because nobody's touched it in a while.
